name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-go .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-go

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hello-go \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-go \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
